version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: milad
      MONGO_INITDB_DATABASE: chatify
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: [--bind_ip_all, --auth]      

  # backend:
  #   build: ./backend
  #   container_name: backend
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     MONGODB_URI: mongodb://root:milad@mongodb:27017/bookstore?authSource=admin
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules

volumes:
  mongodb_data: