name: Chatify-app CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'

      - name: Install and build backend
        run: |
          cd backend
          npm install
          npm run build

      - name: Install and build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Copy frontend to backend
        run: node copy-frontend.js

      - name: Verify build
        run: |
          echo "=== Build Verification ==="
          ls -la backend/dist/frontApp/ && echo "✅ FrontApp copied successfully" || echo "❌ FrontApp not found"
          [ -f backend/dist/app.js ] && echo "✅ Backend built successfully" || echo "❌ Backend build failed"